name: tour_a_vlog
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  onboarding: ^3.1.0
  intl_phone_field: ^3.1.0
  readmore: ^2.2.0
  intl: ^0.18.0
  flutter_credit_card: ^3.0.4
  dotted_border: ^2.0.0+2
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.5
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  geolocator: ^9.0.2
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.3
  path: ^1.8.2
  path_provider: ^2.0.13
  camera: ^0.10.3+2
  permission_handler: ^10.2.0
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.1
  firebase_core: ^2.13.0
  carousel_slider: ^4.2.1
  image_picker: ^0.8.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/onboarding/
    - assets/auth/
    - assets/bottomavigation/
    - assets/home/
    - assets/internationaldestination/
    - assets/detail/
    - assets/thingstodo/
    - assets/packages/
    - assets/packagedetail/
    - assets/restaurantdetail/
    - assets/placedetail/
    - assets/search/
    - assets/topdestination/
    - assets/topindiandestination/
    - assets/review/
    - assets/similarplace/
    - assets/upcomingEvent/
    - assets/hoteldetail/
    - assets/creditcard/
    - assets/success/
    - assets/cabsdetails/
    - assets/notification/
    - assets/searchcab/
    - assets/trains/
    - assets/favorite/
    - assets/profile/
    - assets/location/
    - assets/languages/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
          weight: 200
        - asset: fonts/Poppins-Medium.ttf
          weight: 100
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500